{% set name = "wordfreq" %}
{% set version = "3.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wordfreq-{{ version }}.tar.gz
  sha256: 7943098975f25c2a70e1151ee5a62083b14a5f86f6cc5703cc9526f716ceb408

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4
    - msgpack-python >=1.0.7,<2.0.0
    - langcodes >=3.0
    - regex >=2023.10.3
    - ftfy >=6.1
    - locate >=1.1.1,<2.0.0
    

test:
  imports:
    - wordfreq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/LuminosoInsight/wordfreq/
  summary: Python library for looking up the frequencies of words in many languages.
  license: MIT
  license_file: MIT-LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
